FORMAT: 1A
HOST: http://iitest.api.youxiamotors.com/

# 游侠汽车用户 API
游侠汽车用户 API 用于向用户提供控制汽车以及查询汽车信息的功能。

请注意，在访问这些接口的时候，服务器会设置一些 cookies，用于记录会话信息。请务必保存和回传这些 cookies。如果忽略 cookies，会导致一些奇怪的问题，如在发送注册短信的时候总是提示“验证码错误”。

一般情况下，接口返回的消息均为 JSON 格式，其结构如下：

    {
        "code": 0,  /** 状态码 0 表示操作成功，如果非 0 则表示操作失败，message 属性中会包含错误描述 */
        "message": "成功时可能包含一些成功描述信息，如果出错的话会包含错误描述信息",
        "data": {}  /** 一些额外的数据 */
    }

code 属性值代表的意义在下表中列出：

| code      |      描述      | 
|-----------| :------------- |
| 0         | 操作正常完成 |
| -10001    | 密码不正确   |
| -10002    | 手机号码非法 |
| -10003    | 缺少必传参数 |
| -10004    | 手机短信注册验证码不正确 |
| -10005    | 手机号码已被注册 |
| -10006    | 电子邮件地址已被注册 |
| -10007    | 手机注册验证码码短信已发送，请稍后再请求重新发送 |
| -10008    | 需要输入图形验证码（CAPTCHA） |
| -10009    | 图形验证码不正确 |
| -10010    | 登录后才能执行此操作 |
| -10011    | 没有访问此接口的权限 |





# Group 注册

注册相关接口共有三个，分别是

* 创建账户 `/register/create`
* 获取注册短信验证码 `/register/vericode`
* 获取“获取注册短信验证码”的验证码 `/register/captcha`

一个典型的注册过程如下：

1. 收集用户信息 ( 向用户显示注册表单 )
1. 要求发送注册短信验证码 ( `/register/vericode` )
1. 如果服务器返回无法发送注册短信验证码，就获取“获取注册短信验证码”的图形验证码，然后尝试重新要求服务器发送短信验证码 ( `/register/captcha` )
1. 将短信验证码和用户信息提交给服务器进行注册 ( `/register/create` )

其中一个特殊之处是，调用 /register/vericode 接口时不一定需要提供 captcha 参数，也就是说不需要用户输入验证码。只有当服务器返回失败的时候，才需要提供 captcha 参数，也就是说这时候才需要用户输入验证码。
这样就可以让大部分用户在注册的时候不需要输入验证码，有助于提高用户体验。

一般来说，只有当某个 IP 短时间内频繁访问 /register/vericode 接口时，来自这个 IP 的用户才需要输入图形验证码。

用户注册之后可以与自己的汽车进行关联，也可以获得对他人汽车的使用授权。

### GET /register/create?cellphone={cellphone}&email={email}&password={password}&name={name}&vericode={vericode}

**创建账户**

将用户注册信息提供给服务器，创建用户账户。

+ Parameters
    + cellphone (<string>, `13800138000`) ... 用户手机号码，注册成功之后没有关联汽车的用户可以使用手机通过收取短信的方式找回密码
    + email (optional,<string>,`user@example.com`) ... 用户的电子邮件地址
    + password (<string>, `123456abcd`) ... 用户的账户密码
    + name  (<string>, optional, `nickname`) ... 用户昵称
    + vericode (<string>, required, `901384`) ... 注册短信验证码，注册前需要向手机发送短信验证码，确认手机号码之后才能创建账户
    
+ Request (application/x-www-form-urlencoded)
    
+ Response 200 (application/json)

    + Header
    
            Set-Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7; path=/
            
    + Body
    
            {
                "code": 0,
                "message": "用户注册成功"
            }
        

### GET /register/vericode?cellphone={cellphone}&captcha={captcha}

**获取注册短信验证码**

用户注册的时候需要验证手机号码，可以通过此接口要求系统向用户手机发送短信验证码。

+ Parameters
    + cellphone (<string>, `13800138000`) ... 用于接收注册短信验证码的手机号码
    + captcha (<string>, optional, `ab3x`) ... 为了防止短信接口被滥用，用户有可能需要输入验证码后才能获取注册验证码短信。一般情况下不需要用户输入验证码就能发送注册短信，但如果接口返回无法发送验证码之类的错误，请要求用户输入验证码，然后再次调用此接口。
    
+ Request (application/x-www-form-urlencoded)
    
+ Response 200 (application/json)

    + Header
    
            Set-Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7; path=/

    + Body

            {
                "code": 0,  /** 如果不为 0,可以尝试要求用户输入验证码之后再重新请求此接口 */
                "message": "注册验证码短信发送成功",
                "data": {
                    "cooldown": 120  /** 需要等待多少秒后才能再次要求发送短信 */
                }
            }
        

### GET /register/captcha

**获取“获取注册短信验证码”的验证码**

为了防止短信接口被滥用，在某些情况下，获取注册验证短信时需要输入图形验证码，可以通过这个接口来获取图形验证码图片，并将验证码图片展现给用户。

输入图形验证码上的字母时，可以不区分大小写。

+ Request (text/html)

    + Header
    
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
    
+ Response 200 (image/png)

    + Header
    
            Set-Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7; path=/


# Group 会话（登录和注销）

### GET /session/login?cellphone={cellphone}&&password={password}&captcha={captcha}

**登录**

进行用户登录操作，只有登录之后才能进行其他针对汽车和账户的操作。

会话信息是保存在 cookies 中的，所以请务必保存服务器返回的 cookies，在向服务器发送请求时，也应该发送 cookies.

一般情况下，登录的时候不需要输入图形验证码。但如果服务器认为当前有人正在进行恶意攻击，就会要求输入图形验证码，在这种情况下，该接口会返回“需要输入图形验证码”的错误信息，用户只需要访问 `/session/captcha` 接口获取验证码，输入验证码之后再次提交登录请求即可。

+ Parameters
    + cellphone (<string>, `13800138000`) ... 用户手机号码
    + password (<string>, `123456abcd`) ... 用户的密码明文
    + captcha (<string>, optional, `4a3b`) ... 图形验证码，一般情况下不需要发送图形验证码，当服务器认为有人恶意攻击时，会要求输入图形验证码
    
+ Request (application/x-www-form-urlencoded)
    
+ Response 200 (application/json)

    + Header
    
            Set-Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7; path=/
            
    + Body
    
            {
                "code": 0,
                "message": "登录成功"
            }
        

### GET /session/captcha

**获取登录图形验证码**

获取登录时需要输入的图形验证码。

+ Request (application/x-www-form-urlencoded)

    + Header
    
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7

+ Response 200 (image/png)

    + Header
    
            Set-Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7; path=/


### GET /session/logout

**注销**

注销，即退出登录。虽然理论上来说，要注销会话只需要将本地的 cookies 删除即可，但出于安全考虑，我们还是建议先访问此接口，再将本地的 cookies 删除。

+ Request (application/x-www-form-urlencoded)
    
    + Header
    
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7

+ Response 200 (application/json)

    + Header
    
            Set-Cookie: sid=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=-1
            
    + Body
    
            {
                "code": 0,
                "message": "注销成功"
            }
        


### GET /session/history?no={no}&limit={limit}&order={order}

**获取登录历史**

获取用户的历史登录记录，每次最多可以获取 100 条记录。

该接口须要登录之后才能使用。

+ Parameters

    + no = `1` (<int>, optional, `11`) ... 从第几条记录开始获取，第一条记录的序号是 1
    + limit = `10` (<int>, optional, `10`) ... 要获取的记录数量
    + order = `desc` (<int>, optional, `asc`) ... 登录历史列表按照时间排列，可以用这个参数指定是升序排列还是降序排列，可选值为 _asc_ 或 _desc_

+ Request (application/x-www-form-urlencoded)

    + Header
    
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
            

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "操作成功",
                "data": {
                    "count": 113,   /** 用户登录记录总数 */
                    "no": 11,
                    "limit": 2,
                    "history": [
                        {
                            "successed": true,         /** 登录是否成功，成功为 true，失败为 false */
                            "time": 1411032503,     /** 登录时间，格式为 UNIX 时间戳 */
                            "source": "api",        /** 登录来源 */
                            "ip": "118.158.55.64"   /** 客户端 IP 地址 */
                        },
                        {
                            "successed": true,         /** 登录是否成功，成功为 true，失败为 false */
                            "time": 1411031100,     /** 登录时间，格式为 UNIX 时间戳 */
                            "source": "api",        /** 登录来源 */
                            "ip": "118.158.55.64"   /** 客户端 IP 地址 */
                        }
                    ]
                }
            }
        




# Group 汽车授权（Car Authorization）

### GET /authorization/create?cellphone={cellphone}&&serial_no={password}&duration={duration}&expiration={expiration}

**创建授权**

将汽车的使用权授予其他用户。

授权方式有两种，一种是有期限授权，一种是长期授权。在有期限授权的情况下，受权用户只能使用汽车一段时间，这段时间的长短由授权人指定。在长期授权的情况下，受权用户可以一直使用汽车。

不论是有期限授权还是长期授权，汽车所有者都可以随时撤销授权。

要进行有期限授权，可以使用 _duration_ 或 _expiration_ 其中一个参数来指定授权时间，如果同时指定了两个参数，那么将以授权时间更短的那个参数为准。

要进行长期授权，只需要省略 _duration_ 和 _expiration_ 参数即可。

+ Parameters
    + cellphone (<string>, `13800138000`) ... 受权用户的手机号码
    + serial_no (<string>, `25b0b035-766a-49b1-8cd8-ceabb26f96d2`) ... 要授权的汽车的序列号
    + duration (<string>, optional, `86400`) ... 授权时长，单位为秒。受权用户只能在接下来的这么长的时间内使用汽车
    + expiration (<string>, optional, `1411197724`) ... 授权截止期，格式为 UNIX 时间戳。受权用户只能在这个时间之前使用汽车
    
+ Request (application/x-www-form-urlencoded)

    + Header
            
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
    
+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "授权成功",
                "data": {
                    "authorization_id": 118869, /// 授权记录编号
                    "cellphone": 13800138001,   /// 受权用户的手机号码
                    "serial_no": "25b0b035-766a-49b1-8cd8-ceabb26f96d2",    /// 授权的汽车的序列号
                    "duration": 86400,           /// 授权时长
                    "expiration": 1411197724    /// 授权到期时间
                }
            }
        



### GET /authorization/delete?authorization_id={authorization_id}

**撤销授权**

撤销曾经授予给其他用户的汽车使用授权。

+ Parameters
    + authorization_id (<string>, `118869`) ... 授权编号

+ Request (application/x-www-form-urlencoded)

    + Header
            
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
    
+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "授权撤销成功"
            }
        


### GET /authorization/list?no={no}&limit={limit}&order={order}&serial_no={serial_no}

获取用户名下汽车的授权记录列表

+ Parameters

    + no = `1` (<int>, optional, `11`) ... 从第几条记录开始获取，第一条记录的序号是 1
    + limit = `10` (<int>, optional, `10`) ... 要获取的记录数量
    + order = `desc` (<int>, optional, `asc`) ... 授权记录列表按照授权时间排列，可以用这个参数指定是升序排列还是降序排列，可选值为 _asc_ 或 _desc_
    + serial_no = `` (<string>, optional, `25b0b035-766a-49b1-8cd8-ceabb26f96d2`) ... 如果指定了汽车序列号，则只列出有关该汽车的授权记录

+ Request (application/x-www-form-urlencoded)

    + Header
    
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
            

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "操作成功",
                "data": {
                    "count": 113,   /** 授权记录总数 */
                    "no": 11,
                    "limit": 1,
                    "history": [
                        {
                            "authorization_id": 76
                            "serial_no": "25b0b035-766a-49b1-8cd8-ceabb26f96d2",    /** 授权的汽车序列号 */ 
                            "cellphone": 13800138001,   /** 受权人的手机号码 */
                            "effective": true,          /** 授权是否有效，如果授权已被撤销或已经超过授权时间，则授权无效，否则授权有效 */
                            "etime": 1411197724,        /** 授权到期时间，格式为 UNIX 时间戳 */
                            "ctime": 1411112304,        /** 授权记录创建时间 */
                            "rtime": null,              /** 授权被撤销的时间，如果为 null 表示授权没有被撤销，否则表示授权已经被撤销了，格式为 UNIX 时间戳 */
                        }
                    ]
                }
            }
        

### GET /authorization/users?serial_no={serial_no}

获取汽车名下当前拥有有效授权的所有用户的名单

+ Parameters
    + serial_no (<string>, `25b0b035-766a-49b1-8cd8-ceabb26f96d2`) ... 汽车的序列号。如果不传此参数，则列出当前用户名下所有汽车的所有拥有有效授权的用户名单。如果传递了此参数，则只列出指定汽车下拥有有效授权的用户名单
    
+ Request (application/x-www-form-urlencoded)

    + Header
            
            Cookie: sid=l2o23e1ntv3e01nt9qesdnrhp7
    
+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "操作成功",
                "data": {
                    "users": [
                        {
                            "cellphone": 13800138001,   /** 受权用户的手机号码 */
                            "serial_no": ""25b0b035-766a-49b1-8cd8-ceabb26f96d2"    /** 授权的汽车序列号 */
                        }
                    ]
                }
            }
        








